// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyqaeaygyunakhhxgzfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cWFlYXlneXVuYWtoaHhnemZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODcyODMsImV4cCI6MjA2NTU2MzI4M30.-bv_9fmIMAKJ8GJEaUSMY63FDdkw5Yrz4sih41iIXCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);